export const PLANS =[
    {
        name:"FREE",
        slug:"free",
        quota:10,
        pagesPerPDF:5,
        price:{
            amount:0,
            priceIds:{
                test:"",
                production:"",
            }
        }
    },
    {
        name:"Pro",
        slug:"pro",
        quota:50,
        pagesPerPDF:25,
        price:{
            amount:145,
            priceIds:{
                test:"price_1Oh7mbSFrQfS67HKuNFzaV6F",
                production:"",
            }
        }
    }
]